#version 450

struct Particle {
    vec2 position;
    vec2 velocity;
    vec4 color;
};

layout(set = 0, binding = 0) readonly buffer ParticleSSBOIn {
    vec3 particlesIn[];
};

layout(set = 0, binding = 1) buffer ParticleSSBOOut {
    vec3 particlesOut[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    vec3 particleIn = particlesIn[index];

    particlesOut[index] = particleIn;
}